### ISSUE TITLE
[STORM-167] proposal for storm topology online update

### ISSUE THREAD

**Issue by jira-importer** [apache/storm#4009]
<p><a href="https://github.com/nathanmarz/storm/issues/540" class="external-link" target="_blank" rel="nofollow noopener">https://github.com/nathanmarz/storm/issues/540</a></p>

<p>Now update topology code can only be done by kill it and re-submit a new one. During the kill and re-submit process some request may delay or fail. It is not so good for online service. So we consider to add topology online update recently.</p>

<p>Mission</p>

<p>update running topology code gracefully one worker after another without service total interrupted. Just update topology code, not update topology DAG structure including component, stream and task number.</p>

<p>Proposal</p>

<ul>
	<li>client use "storm update topology-name new-jar-file" to submit new-jar-file update request</li>
	<li>nimbus update stormdist dir, link topology-dir to new one</li>
	<li>nimbus update topology version on zk</li>
	<li>the supervisors that running this topology update it
	<ul>
		<li>check topology version on zk, if it is not the same as local version, a topology update begin</li>
		<li>each supervisor schedule the topology's worker update at a rand(expect-max-update-time) time point</li>
		<li>sync-supervisor download the latest code from nimbus</li>
		<li>sync-process check local worker heartbeat version(to be added), if it is not the same with sync-supervisor downloaded version, kill the worker</li>
		<li>sync-process restart killed worker</li>
		<li>new worker heartbeat to zk with version(to be added), it can be displayed on web ui to check update progress.</li>
	</ul>
	</li>
</ul>

<p>This feature is deployed in our production clusters. It's really useful for topologys handling online request waiting for response. Topology jar can be updated without entire service offline.</p>

<p>We hope that this feature is useful for others too.</p>

---
<details><summary><i>Originally reported by <a title="James Xu" href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=xumingming">xumingming</a>, imported from: <a href="https://issues.apache.org/jira/browse/STORM-167" target="_blank">proposal for storm topology online update</a></i></summary>
<i><ul>
<li><b>assignee</b>: <a title="Parth Brahmbhatt" href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=parth.brahmbhatt">parth.brahmbhatt</a>
<li><b>status</b>: Closed
<li><b>priority</b>: Minor
<li><b>resolution</b>: Abandoned
<li><b>resolved</b>: 2024-07-02T10:54:46+01:00
<li><b>imported</b>: 2025-01-24
</ul></i>
</details>

**Comment by jira-importer** [comment]
Subtasks:

- STORM-1345
- STORM-1346
- STORM-1347

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=az">az</a>:</i>
<p><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=xumingming" class="user-hover" rel="xumingming">James Xu</a> It sounds like you have implemented this - if so, is this story resolved?  </p>

<p> I also would really like this feature, and was thinking of building it, but I won't if it is already done..</p>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=xiaokang">xiaokang</a>:</i>
<p>hi <a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=az" class="user-hover" rel="az">Aaron Zimmerman</a> , I've submitted a pull request on the old storm git repo <a href="https://github.com/nathanmarz/storm/pull/741" class="external-link" target="_blank" rel="nofollow noopener">https://github.com/nathanmarz/storm/pull/741</a>. </p>

<p>The core code modification is about 300 lines and many others are generated by thrift. We have deployed this feature on production clusters about 6 months. Any advice is welcome!</p>

<p><b>main points:</b></p>

<p><b>1. interface changes (compatible with old versions)</b><br/>
1.1 zk add :topology-version and :update-duration-sec fields to StormBase:status map<br/>
1.2 zk add :topology-version to executor heartbeat<br/>
1.3 worker local state add versions dir to storm worker's current running topology-version<br/>
1.4 nimbus add updateTopology interface<br/>
1.5 add topology-version field to storm.thrift three struct: TopologySummary ExecutorSummary TopologyInfo</p>

<p><b>2. topology update process</b><br/>
2.1 storm client run "storm jar xxxx -c topology.update=true" to invoke topology update process<br/>
2.2 storm client upload new jar file to nimbus<br/>
2.3 storm client call nimbus updateTopology interface<br/>
2.4 nimbus check the new topology and replace stormdist/storm-id dir<br/>
2.5 nimbus update StormBase in zk, set :topology-version(for destination version) and :update-duration-sec(for all workers update process duration) fields to StormBase:status map<br/>
2.6 supervisors check zk StormBase and do the update work if topology's local version is not the same with zk version<br/>
2.6.1 sync-supervisor download the latest code from nimbus to local stormdist/topology-version dir<br/>
2.6.2 each supervisor schedule the topology's worker update at a rand(expect-max-update-time) time point<br/>
2.6.3 sync-process check local worker version, if it is not the same with sync-supervisor downloaded version and update time point reached, set worker state to a new :update state<br/>
2.6.4 sync-process kill workers in :update state as normally<br/>
2.6.5 sync-process restart killed worker as normally, expect that read topology and conf from stormdist/topology-version dir<br/>
2.6.6 new worker heartbeat to zk with new topology-version, it can be displayed on web ui to check update progress</p>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=danehammer">danehammer</a>:</i>
<p>I need this. There's already a lot of work done. What can I do to get this merged to master? Looks like some rebasing and correcting merge conflicts is in order, but what about approval of the design - is this how we want to do this?</p>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=samuel hsieh">samuel hsieh</a>:</i>
<p>Does this feature denote the 'storm swap' in the release plan introduced in the documentation?<br/>
<a href="https://storm.apache.org/documentation/Running-topologies-on-a-production-cluster.html" class="external-link" target="_blank" rel="nofollow noopener">https://storm.apache.org/documentation/Running-topologies-on-a-production-cluster.html</a></p>

<p>This topology rolling upgrade feature is important for streaming computing for real-life application, what support we can do for the feature/design approval? Thanks.</p>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=soag">soag</a>:</i>
<p>Is there any news on this? Really would like to see this feature go into a release soon..</p>

<p>Thanks</p>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=parth.brahmbhatt">parth.brahmbhatt</a>:</i>
<p> This is a useful feature and I see a lot of user interest.</p>

<p><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=xiaokang" class="user-hover" rel="xiaokang">Kang Xiao</a> Thanks for the original patch and I am not sure why it was not reviewed. Do you think you can upmerge this with storm/master? If not, do you mind if I take over this task? </p>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=parth.brahmbhatt">parth.brahmbhatt</a>:</i>
<p> This is a useful feature and I see a lot of user interest.</p>

<p><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=xiaokang" class="user-hover" rel="xiaokang">Kang Xiao</a> Thanks for the original patch and I am not sure why it was not reviewed. Do you think you can upmerge this with storm/master? If not, do you mind if I take over this task?</p>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=soag">soag</a>:</i>
<p>Hi <a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=parth.brahmbhatt" class="user-hover" rel="parth.brahmbhatt">Parth Brahmbhatt</a>,</p>

<p>Just wondering if there is any update on this feature?</p>

<p>Thanks Roland</p>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=parth.brahmbhatt">parth.brahmbhatt</a>:</i>
<p>Hey , I haven't had time to look into this yet and I am busy with some other stuff so probably wont get to it in next 2 months. If someone else wants to take it up please feel free to do so.</p>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=samuel hsieh">samuel hsieh</a>:</i>
<p>Hi Parth Brahmbhatt,<br/>
Is there any news on this? It's an important feature and may we raise the priority to higher?<br/>
or what support we can do for the feature/design approval? <br/>
Thanks.</p>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=parth.brahmbhatt">parth.brahmbhatt</a>:</i>
<p>Sorry I have been busy wit some other stuff at work. Let me see if I can finish the work in coming 2 weeks. </p>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=samuel hsieh">samuel hsieh</a>:</i>
<p>Hi Parth Brahmbhatt,</p>

<p>Any validation support needed pls feel free to let us know and many thanks for your great contribution!!</p>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=rzo1">rzo1</a>:</i>
<p>We are in the process of migrating our issue tracking system to GitHub issues. This issue has been stale for the last 5 years, and STORM has evolved with many dependency updates since this issue was last updated.</p>

<p>If the issue persists in the latest version of Storm, please feel free to reopen it or provide new context. Thank you very much!</p>

**Comment by Gowtham-Gowts** [comment]
@rzo1 
This feature is not available, must needed one. Please reopen it.

@Parth-Brahmbhatt
