### ISSUE TITLE
[STORM-3314] Acker redesign

### ISSUE THREAD

**Issue by jira-importer** [apache/storm#7096]
<p><b>Context:</b> The ACKing mechanism has come focus as one of the next major bottlenecks to address. The strategy to timeout and replay tuples has issues discussed in <a href="https://issues.apache.org/jira/browse/STORM-2359" title="Revising Message Timeouts" class="issue-link" data-issue-key="STORM-2359"><del>STORM-2359</del></a></p>

<p><b>Basic idea:</b> Every bolt will send an ACK msg to its upstream spout/bolt once the tuples it emitted have been <b>fully processed</b> by downstream bolts.</p>

<p><b>Determining "fully processed”</b> : For every incoming (parent) tuple, a bolt can emit 0 or more “child” tuples. the Parent tuple is considered fully processed once a bolt receives ACKs for all the child emits (if any). This basic idea cascades all the way back up to the spout that emitted the root of the tuple tree.</p>

<p>This means that, when a bolt is finished with all the child emits and it calls ack() no ACK message will be generated (unless there were 0 child emits). The ack() marks the completion of all child emits for a parent tuple. The bolt will emit an ACK to its upstream component once all the ACKs from downstream components have been received.</p>

<p><b>Operational changes:</b> The existing spouts and bolts don’t need any change. The bolt executor will need to process incoming acks from downstream bolts and send an ACK to its upstream component as needed. In the case of 0 child emits, ack() itself could immediately send the ACK to the upstream component. Field grouping is not applied to ACK messages.</p>

<p>Total ACK messages: The spout output collector will no longer send an ACK-init message to the ACKer bolt. Other than this, the total number of emitted ACK messages does not change. Instead of the ACKs going to an ACKer bolt, they get spread out among the existing bolts. It appears that this mode may reduce some of the inter-worker traffic of ACK messages.</p>

<p><b>Memory use:</b> If we use the existing XOR logic from ACKer bolt, we need about 20 bytes per outstanding tuple-tree at each bolt. Assuming an average of say 50k outstanding tuples at each level, we have 50k*20bytes = 1MB per bolt instance. There may be room to do something better than XOR, since we only need to track one level of outstanding emits at each bolt.</p>

<p><b>Replay:</b> <span class="error">&#91;needs more thinking&#93;</span> One option is to send REPLAY or TIMEOUT msgs upstream. Policy of when to emit them needs more thought. Good to avoid Timeouts/replays of inflight tuples under backpressure since this will lead to "event tsunami" at the worst possible time. Ideally, if possible, replay should be avoided unless tuples have been dropped. Would be nice to avoid sending TIMEOUT_RESET msgs upstream when under backpressure ... since they are likely to face backpressure as well.</p>

<p>On receiving an ACKs or REPLAYs from downstream components, a bolt needs to clears the corresponding 20 bytes tracking info.</p>

<p> </p>

<p><b>Concerns:</b> ACK tuples traversing upstream means it takes longer to get back to Spout.</p>

<p> </p>

<p> </p>

<p><b>Related Note:</b> <ins>Why ACKer is slow ?:</ins></p>

<p>Although lightweigh internally, the ACKer bolt has a huge impact on throughput. The latency hit does not appear to be as significant.</p>

<p>I have some thoughts around why ACKer slows down throughput. </p>

<p>Consider the foll simple topo: </p>

<p><tt>Spout ==> Bolt1 ==> Bolt2</tt></p>

<p>If we add an ACKer to the above topo, the Acker bolt receives 3x more incoming messages than the Bolt1 & Bolt2. Thats instantly a 3x hit on its throughput on ACKer. Additionally each spout and bolt now emits 2 msgs instead of 1 (if acker were absent). This slows down the spouts and bolts.</p>

---
<details><summary><i>Originally reported by <a title="Roshan Naik" href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=roshan_naik">roshan_naik</a>, imported from: <a href="https://issues.apache.org/jira/browse/STORM-3314" target="_blank">Acker redesign</a></i></summary>
<i><ul>
<li><b>status</b>: Closed
<li><b>priority</b>: Major
<li><b>resolution</b>: Abandoned
<li><b>resolved</b>: 2024-07-02T10:54:50+01:00
<li><b>imported</b>: 2025-01-24
</ul></i>
</details>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=roshan_naik">roshan_naik</a>:</i>
<p><em>Quoting thoughts expressed by</em> <a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=kabhwan" class="user-hover" rel="kabhwan">Jungtaek Lim</a> <em>in response to above initial idea :</em></p>

<p> </p>

<p><b>Essential idea:</b> Try to avoid sending ack tuple to another workers, given that it incurs serde and network cost. If we could get rid of field grouping it may be better.</p>

<p>Roshan brought a great idea about it, which is in line with my essential idea, so there may be a trade-off between Roshan’s and mine. My idea is inspired by Roshan’s idea and a bit modified to adopt nice things of his idea.</p>

<p> </p>

<p><b>Summary:</b> Build partial tuple tree into Acker in each worker, and let Acker in worker handles its own partial tuple tree. Note that we don’t change the basic idea of acking mechanism.</p>

<p> </p>

<p><b>Detail:</b></p>
<ul>
	<li>When tuple is emitted from spout, it sends ACK_INIT message to Acker within worker.
	<ul>
		<li>Same as current.</li>
	</ul>
	</li>
</ul>


<p> </p>
<ul>
	<li>The logic for emitting tuple in Bolt doesn’t change.
	<ul>
		<li>We may want to include acker ID to the tuple to send acknowledge to.</li>
		<li>Otherwise, we also could compute (and cache) it from bolt side (based on source task ID) to not grow size of each tuple.</li>
	</ul>
	</li>
	<li>When worker receives tuples from outside of worker, it also sends ACK_INIT message to Acker within worker.
	<ul>
		<li>Acker stores additional information (acker task ID for source task’s worker, tuple ID of source tuple, anchors, etc.) to “send back ACK to source” when partial tuple tree is completed.</li>
		<li>The information may be a bit different between referring spout and referring another acker.</li>
	</ul>
	</li>
	<li>Whenever tuple is acknowledged in Bolt, ACK message is sent to the acker within worker.</li>
	<li>When acker found tuple tree is completed, it sends back ACK to source acker based on stored information.
	<ul>
		<li>If the source is Spout, just do as same as what we are going.</li>
	</ul>
	</li>
</ul>


<p> </p>

<p><b>Expected benefits:</b></p>
<ul>
	<li>ACK tuples between hops within worker will not be sent to another workers, hence avoiding cost of serde and network transfer.</li>
	<li>No field grouping.</li>
	<li>It follows the path how tuples are flowing, which could be optimized by grouper implementation.</li>
</ul>


<p> </p>

<p><b>Considerations:</b></p>
<ul>
	<li>Each worker has to have acker task for each, which is a new requirement even it is by default for now.
	<ul>
		<li>We could (and should) still turn off acker when needed, but configuration for acker needs to be changed to turn on/off, not acker task count.</li>
	</ul>
	</li>
	<li>Total count of ack tuples is not changed.
	<ul>
		<li>Maybe we could avoid sending ACK tuples within worker and just calculate and update what acker is doing on the fly (in executor thread) if it gives more benefits.</li>
	</ul>
	</li>
	<li>A bit more memory is needed given that we maintain tuple tree for each worker (linear to worker count tuple tree has to flow), and we need additional information for sending back ACK to another acker.</li>
	<li>Need to consider how FAIL tuple will work, and how RESET_TIMEOUT tuple will work.
	<ul>
		<li>They will be going to be headache things to consider from both mine and Roshan’s.</li>
		<li>I’m still not sure how tuple timeout works with backpressure, even we still need this to get rid of old things in rotating tree.</li>
	</ul>
	</li>
</ul>


<p> </p>

<p><b>Differences between Roshan’s idea:</b></p>
<ul>
	<li>We don’t add ACK tuples to the source task’s queue, hence keep bolt’s task and acker’s task separate.
	<ul>
		<li>Two perspectives: queue, (executor) thread.</li>
		<li>It will be less coupled with backpressure. IMHO, ACK tuples and metrics tuples should flow regardless of backpressure ongoing.</li>
		<li>I think leaving it to separate could keep opening possibilities to apply more optimizations on acker, like having separate channel for ACK tuples and metrics tuples.</li>
	</ul>
	</li>
	<li>It uses less memory if there’re some tasks in worker: it is just what acker excels.</li>
	<li>Less ACK tuple flowing hops when ACK tuples are flowing back, given that it only deals with ackers. (Yes, more hops when acking within worker though.)</li>
	<li>We just need to handle rotating tree only one place (acker) for each worker, compared to each task.</li>
	<li>Complicated than Roshan’s idea: Roshan’s idea is just clearly intuitive, and I can’t imagine easier solutions.</li>
</ul>


<p> </p>

<p> </p>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=srdo">srdo</a>:</i>
<p>The core idea of avoiding crossing the worker boundary as much as possible sounds really good.</p>

<p>I think I like Jungtaek's iteration a little better.</p>

<p>I see the following benefits to the second idea over the first:</p>
<ul>
	<li>Using a separate acker task in each worker means we don't have to worry about acks getting queued behind user tuples</li>
	<li>The same worry would apply to timeout resets, and would almost certainly mean that we can't do resetting at all reliably.</li>
	<li>As Jungtaek mentioned, backpressure would be a concern for acks when they're going through the same queues as user tuples</li>
	<li>We keep the ability to add more ackers in each worker if we want.</li>
</ul>


<p>My initial suggestion for how timeouts would work with this setup would be that we move timeout logic entirely to the acker. Since the spout and initial acker are now guaranteed to run in the same worker, we don't need the spout to be timing out tuples by itself, and we don't need to worry about the first ACK_INIT getting lost. </p>

<p>When doing a timeout reset, if we have every acker keep its own timeout, we will need to walk up the tree from the worker that resets the timeout to the root acker. I think we might be able to reduce the number of reset messages here by having only the root acker time out tuples. We can use the sync tuple mechanism I suggested in <a href="https://issues.apache.org/jira/browse/STORM-2359" title="Revising Message Timeouts" class="issue-link" data-issue-key="STORM-2359"><del>STORM-2359</del></a> to make sure downstream ackers don't keep outdated anchors around. This way, we can jump straight to the root, instead of having to walk the tree.</p>

<p>I'll have to think a bit more about automatic timeout resetting. Currently it can be made to work nicely because every ack resets the timeout, which makes it easy to reason about how long we can safely delay resetting tuples. This lets us decide not to reset tuples that have only been present in a worker for a short time, because we know that the tree was likely acked recently, right before it was sent to the worker. If acks don't end up hitting the root acker, we might need to send some extra tuples to ensure timeouts are reset. Maybe we can get away with buffering up acked anchors for a percentage of the message timeout in the acker, and send them as a batch message to the root acker. I'm a little worried about flooding the root acker with reset messages.</p>

<p>Regarding FAIL tuples, if we decide to use sync tuples to keep the root acker and other ackers in sync, we might be able to just send FAILs up the tree to the root acker, and let the sync tuple be responsible for removing it from any branches of the tuple path that didn't get the FAIL. I think trying to ensure all ackers are notified about the FAIL immediately would be hard.</p>

**Comment by Gowtham-Gowts** [comment]
@rzo1 can we revive this?
